name: Deploy main docs/next-js → gh-pages/next-js

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: write-all

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        working-directory: docs/next-js
        run: npm install

      - name: Build docs/next-js demo
        working-directory: docs/next-js
        env:
          BASE_PATH: "/netcdf4-wasm/next-js"
        run: npm run build

      - name: Deploying docs 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/next-js/out
          target-folder: next-js
          clean: false